name: view_model_state
description: A Flutter package that provides a ViewModel base class with built-in state management capabilities.
version: 0.0.7
repository: https://github.com/larnetic/view_model_state
issue_tracker: https://github.com/larnetic/view_model_state/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.26.2
